version: "3.8"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:9.3.8
    restart: always
    ports:
      - "3000:3000"
    volumes:
     - ./grafana:/etc/grafana/provisioning/datasources
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - grafana-network

  loki:
    container_name: loki
    image: grafana/loki:2.8.1
    restart: always
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - grafana-network

  promtail:
    container_name: promtail
    image: grafana/promtail:2.8.1
    restart: always
    volumes:
      - ./promtail:/etc/promtail
      - ./logs:/var/log
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - grafana-network
  

  # Serviço do Prometheus adicionado
  prometheus:
    image: prom/prometheus:v2.37.1
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=360h'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - grafana-network

networks:
 grafana-network:


volumes:
  grafana_data:
  prometheus_data: